version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    ports:
      - 5432:5432
  web_app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/usr/src/personalised_nudges
    ports:
      - 80:80
    depends_on:
      - db
